#!/usr/bin/env bash

##
# This file is part of the JAT-Box project
#
# node: This script can be used on a slave machine to connect it to the server
# machine and allow the slave machine to run browser-dependent tests.
################################################################################

# get the directory in which this script is stored
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${DIR}/_common
launch-selenium-server node